max_body_size: 1000mb
storage: tmp/registry
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  github:
    url: https://npm.pkg.github.com/
    auth:
      type: bearer
      token_env: true
packages:
  "@winglang/wing":
    access: $all
    publish: $all
  "@winglang/wingsdk":
    access: $all
    publish: $all
  "@winglang/*":
    access: $all
    proxy: github
  "**":
    access: $all
    proxy: npmjs
logs: { type: stdout, format: pretty, level: error }