name: "Build Failure Notification"

on:
  check_run:
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-22.04
    if: |
      github.event.check_run.name != 'Build Failure Notification'
      && github.event.check_run.conclusion == 'failure' 
      && github.event.check_run.check_suite.head_branch == 'main'
      && github.event.check_run.check_suite.status == 'completed'
    steps:
      - name: Send slack notification
        uses: ravsamhq/notify-slack-action@v2.3.0
        with:
          status: ${{ github.event.check_run.conclusion }}
          notification_title: "${{ github.event.check_run.name }} has failed"
          message_format: ":x *${{ github.event.check_run.name }}* failed in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
          footer: "<${{ github.event.check_run.details_url }}|Details>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
