name: Create Release Comment

on:
  release:
    types:
      - published

jobs:
  release:
    name: "Post release comments"
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          skip-label: pr/backport
          comment-template: |
            Congrats! :rocket: This was released in {release_link}.
