name: Trigger Playground Update

on:
  release:
    types:
      - published

jobs:
  update-playground:
    name: Dispatch playground release workflow event
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/winglang/playground/actions/workflows/52580441/dispatches -d '{"ref":"main"}'
        env:
          GITHUB_TOKEN: ${{ secrets.PROJEN_GITHUB_TOKEN }}
